name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Dostosuj, jeśli używasz innego brancha jako głównego

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # Branch, na który będą deployowane pliki
          folder: dist # Folder z plikami do deploymentu
